export const levelVideos = [
  '01-lock.mp4',
  '02-entrance.mp4',
  '02-visioner-ghosts.mp4',
  '03-visioner-convulsions.mp4',
  '04-visioner-ghosts.mp4',
  '05-visioner-spit.mp4',
  '06-lawyer-visits-ghosts.mp4',
  '07-lawyer-visits-ghosts.mp4',
  '08-lawyer-visits-ghosts.mp4',
  '09-lawyer-sees-girl.mp4',
  '10-lawyer-dies.mp4',
  '11-girl-bathroom-start.mp4',
  '12-girl-bathroom-with-ghost.mp4',
];
