export const levelVideos = [
  { src: '01-lock.mp4', duration: 33 },
  { src: '02-entrance.mp4', duration: 32 },
  { src: '02-visioner-ghosts.mp4', duration: 15 },
  { src: '03-visioner-convulsions.mp4', duration: 10 },
  { src: '04-visioner-ghosts.mp4', duration: 32 },
  { src: '05-visioner-spit.mp4', duration: 10 },
  { src: '06-lawyer-visits-ghosts.mp4', duration: 23 },
  { src: '07-lawyer-visits-ghosts.mp4', duration: 20 },
  { src: '08-lawyer-visits-ghosts.mp4', duration: 20 },
  { src: '09-lawyer-sees-girl.mp4', duration: 25 },
  { src: '10-lawyer-dies.mp4', duration: 49.5 },
  { src: '11-girl-bathroom-start.mp4', duration: 15 },
  { src: '12-girl-bathroom-with-ghost.mp4', duration: 28 },
];
